### ISSUE TITLE
OCPI modules objects base class 

### ISSUE THREAD

**Issue by LiorBenAri** [BitzArt/OCPI.Net#13]
Hi @YuriyDurov,

Did you considered creating a base class for all the OCPI modules objects?
Maybe even only with the common "id", "last_updated" properties.
It might help handling more generically different OCPI modules objects.
Would be happy to hear what you think about this. 

Thanks,
Lior

**Comment by YuriyDurov** [comment]
Hello @LiorBenAri, this idea seems to be coming from a valid place, except that I did not need this in any of my real OCPI implementations. Also, what you are suggesting seems like more of a use case for Interfaces than for base classes. Can you expand on this idea a bit more? Would be interested in hearing what flows you are expecting to implement with this.

Normally, the idea behind this package's contract models would be that you should not be using them directly in your application's [domain logic](https://www.c-sharpcorner.com/article/clean-architecture-in-asp-net-core-web-api/), and that you should instead map them to your internal domain classes and then operate on those. OCPI Contracts are intended to be simply your [DTOs](https://tutorials.eu/data-transfer-objects-in-c-sharp/#:~:text=Data%20Transfer%20Objects%20in%20Web&text=In%20web%20applications%2C%20DTOs%20help,of%20DTOs%20in%20API%20development.). So you can first map the OCPI Contract models to your internal Entities, use those entities in your application logic, and then map them back to DTOs to output in your http response. This should allow you to define your own internal entities and use any interfaces or base classes you want there.

This was always the idea behind OCPI.Net - we provide you with contract models, tools to implement the OCPI protocol, versions module, etc. But we do not force any internal project structure on you, except for maybe some constraints on how your OCPI Module Controllers should look (because of how our implementation of the Versions module works). This way we allow for a flexibility of your own implementation, while simultaneously giving you all the tools to implement OCPI.

Pls do let me know if this is would be enough to solve your questions or if you have more ideas/thoughts on this.

**Comment by LiorBenAri** [comment]
Thanks @YuriyDurov for the explanation - I understand the reasoning of using the OCPI objects only as DTOs.
We are using the modules object of your library, and didn't created an internal objects (probably out of laziness and desire to move forward with our development). 
The flow we need the base class for is - publishing OCPI data (to 3'rd party OCPI service) of all objects types in a generic way. Having the "Id" property on the base class could have help us as a unique identifier property of the published object, that we have all object types.
In general, we are not implementing a OCPI service, we are using 3'rd party OCPI service. We are developing flows to provide the 3'rd party OCPI service all of our OCPI data.

**Comment by YuriyDurov** [comment]
@LiorBenAri Closing for now. Feel free to open if you have more to add to this!

**Comment by LiorBenAri** [comment]
Hi Yuriy,
Sorry for the late response. 
We aren't building an OCPI client app, we are building a pipeline from our CPOs data to a OCPI service that holds our CPOs data and acts as a OCPI service with the classic OCPI endpoints.
For our CPOs data pipeline, we are not using the OCPI endpoints, but rather using a message broker.
Anyway, I used some kind of a hack to get to the id property for all OCPI module objects, so I no longer have this problem.

Thanks anyway,
Lior

**Comment by YuriyDurov** [comment]
Sounds good.
