### ISSUE TITLE
Is OCPI provided from stations?

### ISSUE THREAD

**Issue by Aazme** [BitzArt/OCPI.Net#5]
Hey,

I want to ask about OCPI as I didn't find any resource over the internet, who implements the OCPI? 

There are two parties, the station provider and the mobile app provider. should the station provide the APIs to the provider or the opposite? are there any resources to read from?

**Comment by Aazme** [comment]
Would be great if you could provide any resources to read about OCPI

**Comment by YuriyDurov** [comment]
Hello @Aazme,

This repository contains the latest spec sheet which holds everything you need to know if you are planning on implementing the OCPI protocol: https://github.com/BitzArt/OCPI.Net/blob/main/docs/OCPI-2.2.1.pdf

And here is the original repository of OCPI protocol: https://github.com/ocpi/ocpi

When you are mentioning two parties, I believe you are referring to CPO (Charge Point Operator) and eMSP (e-Mobility Service Provider). If you are planning on connecting two such parties with OCPI, both of them have to implement the protocol. The spec sheet contains detailed requirements on which parts of the protocol each party should implement.

Hope this helps.

You can also reach out to me directly if you have further questions: u.a.durov@gmail.com

**Comment by Aazme** [comment]
Thanks, @YuriyDurov  for your quick reply! I am developing an eMSP app and the CPO tells us they are implementing the OCPI. so I should only follow the OCPI and the APIs and contracts are the same right? only URL change?

**Comment by YuriyDurov** [comment]
@Aazme I suggest that first of all you review the document I mentioned. It contains all the necessary information if you want to implement an eMSP. It would give you a more comprehensive view on what you should be doing in order to achieve your goal.

As for your question: CPOs and eMSPs use the same contracts, but perform different functions and behave differently. These differences, as well as the contracts, are described in OCPI documents like the one I mentioned. I will not be able to guide you on all the details of OCPI implementation as this is too big of a topic, so you should refer to the documentation.

Keep in mind that this particular document is for OCPI version 2.2.1, so first I would suggest that you ask your CPO which particular version of OCPI they implement. Maybe you will need a different one, for the specific version of OCPI that they use.

The nuget package OCPI.Net can provide you with the contracts needed for both the CPO and the eMSP, as well as some basic functionality necessary for every party implementing OCPI protocol. Feel free to use it and reach out if you have any issues with it or if you think it lacks important functionality. I am currently working on extending the package's feature set, so feature suggestions are welcome.

**Comment by Aazme** [comment]
@YuriyDurov  Thanks so much for your response & support and sure will get back to you and even contribute if I could! :)
