### ISSUE TITLE
Do you use any tests' set for OPCI?

### ISSUE THREAD

**Issue by cbelyaev** [BitzArt/OCPI.Net#8]
Hello,

I'm just curious, how do you test your OCPI implementation?
Are you using any test suite? Or did you write something yourself?

**Comment by YuriyDurov** [comment]
Hello @cbelyaev, I have to admit that this library in it's current state lacks tests.

My main way of testing this right now is that I use it in a real implementation of an OCPI service and having that service integrate with other OCPI services in the real world. The library itself does not contain too much logic, right now it is for the most part just a bunch of contracts plus some small functionality like endpoint mapping (for Versions module), which I have tested manually after implementing it. And then again, I am using this in a real implementation myself, and everything seems to work. And I am not planning to change anything logic-wise for some time. So I don't think tests are super important right now.

I am thinking about adding some tests later, but I have more important things to implement first - for example documentation. I think the package lacks documentation more than it lacks unit tests. And I am lacking time to implement everything this package requires 😔

**Comment by YuriyDurov** [comment]
@cbelyaev I am not sure about what you are referring to by 'other services'. Do you mean other OCPI implementations by external parties? Or do you refer to some code in this library?

If you are referring to something in this library, please elaborate what it is in particular.

**Comment by YuriyDurov** [comment]
@cbelyaev 

By that I am referring to external OCPI implementations by third parties. For example, you can implement an eMSP using this package and then have it connect with a real external CPO. Or vice versa - implement a CPO and then have it connect with an external eMSP (e.g. Plugshare)

Those external services are all different - and sometimes have minor deviations from OCPI. They are implemented by external parties and we do not control their implementations.

In general I would say that if you use this library then everything should go smoothly when connecting with them. I have reviewed several real external implementations and now am writing this library in a way that it can support slight deviations in connected platforms like those that I have observed.

If you find any serious deviations in external OCPI implementations and have ideas how to update this library so that it supports working with them - feel free to share!

**Comment by cbelyaev** [comment]
Thanks a lot for your detailed answer!
